### ISSUE TITLE
手机开暗色模式，软件下的字体全部变成白色完全看不见

### ISSUE THREAD

**Issue by 78317280** [YuriSizuku/OnscripterYuri#16]
手机习惯开暗色模式，然后软件进入目录都是白色完全看不见写了啥，必须关闭暗色模式，安卓13手机

**Comment by 78317280** [comment]
就是夜间模式，手机的UI从白色变成黑色。

**Comment by YuriSizuku** [comment]
有截图吗？ 看看如何复现

**Comment by 78317280** [comment]
> 有截图吗？ 看看如何复现
一个是手机开启夜间模式，一个是不开启夜间模式的截图
https://p.inari.site/usr/415/666bd85e32a56.jpg
https://p.inari.site/usr/415/666bd87800791.jpg

**Comment by yujincheng08** [comment]
加个 android:forceDarkAllowed="false" 就行
