### ISSUE TITLE
Android14上每次打开都需要授权文件夹

### ISSUE THREAD

**Issue by 6543x1** [YuriSizuku/OnscripterYuri#18]
![QQ图片20240418174704](https://github.com/YuriSizuku/OnscripterYuri/assets/57287907/2e876755-8af9-46c5-8553-6e99368fc4d5)

Android14下，已经无法选中根目录，似乎高版本的Android修改了相关权限，需要申请MANAGE_EXTERNAL_STORAGE，并使用 Intent.ACTION_MANAGE_ALL_FILES_ACCESS_PERMISSION 操作将用户引导至一个系统设置页面，在该页面上，用户可以为您的应用启用以下选项：授予所有文件的管理权限。
如果选取其他目录（Download目录也不行，提示同上）也可以正常访问，只是每次打开均需要点击sdcard图标来授权

**Comment by YuriSizuku** [comment]
MANAGE_EXTERNAL_STORAGE 这个权限太高了， Google play一般的应用是不给申请的， 你试试新建一个目录， 并且选取？

**Comment by YuriSizuku** [comment]
I will close this issue as no other comments.
