### ISSUE TITLE
Renalith Saga || Crashed booting up the game and certain function not implemented yet (?)

### ISSUE THREAD

**Issue by Grimm-Knight** [YuriSizuku/OnscripterYuri#20]
As I mentioned in the title, when I used the android version. It immediately crash here's where I download the game [Renalith Saga Compressed](https://pixeldrain.com/u/q7EwjStX) This the English version 

Furthermore, someone has checked it. On PC, this certain segment of the game you're unable to click anything. Basically, prevent you to progress 
![FB_IMG_1723997268639](https://github.com/user-attachments/assets/2833b778-6aef-47fe-8fa4-66cb1ca2854d)

Here's a [save file](https://drive.google.com/file/d/1PLA9EnZhIk83Tm7cI1-d3VhqwN4ReeNN/view?usp=drivesdk) to easily recreate the issue

**Comment by YuriSizuku** [comment]
Can you provide `stderr.txt` and `stdout.txt` to show the log ?

**Comment by Grimm-Knight** [comment]
> I have tested it with 0.7.4 windows version and it seems the click works on game.

That's strange. I confirmed the issue as well, and it is there. Below is the video how to recreate the issue and the segment where clicks don't work.

https://github.com/user-attachments/assets/c8aed636-3992-41cf-8080-a22adf3dca68

Also [stderr.txt](https://github.com/user-attachments/files/16660627/stderr.txt) and
[stdout.txt](https://github.com/user-attachments/files/16660633/stdout.txt) as requested. Hopefully it's fixable.

**Comment by YuriSizuku** [comment]
With this video, I can reproduce the problem now. But not sure where cause this problem, can you find the icon image file and tell the name ?

**Comment by Grimm-Knight** [comment]
> can you find the icon image file and tell the name ?

Really sorry for my lack of knowledge, but I'm unsure what you're referring to. Are you asking about the icon image recorded in _stderr.txt,_ like those _BMP_ files? If so, I can't locate it. Or are you referring to the icon image where clicks aren't responsive? You might find all of them in the image directories, such as _/image/va-21.png_

**Comment by YuriSizuku** [comment]
It seems that there are something strong in the script. The `bexec $1` returns `LCLICK` but not the sp num. 
You can try to comment the command `;btndef clear`, and it works now.  

Here's the edited scripts,  you can replace `nscript.dat` with `00.txt`.  
[00.zip](https://github.com/user-attachments/files/16676246/00.zip)


![test_renalithsaga](https://github.com/user-attachments/assets/195e934a-c5c3-4a75-a160-010603ad5d91)

```c
*sin_loop_01

;btndef clear


bexec $1

if $1="S131" goto *idou_kuni_01
if $1="S132" goto *idou_kuni_02
if $1="S133" goto *idou_kuni_03
if $1="S134" goto *idou_kuni_04
if $1="S135" goto *idou_kuni_05
if $1="S136" goto *idou_kuni_06
if $1="S137" goto *idou_kuni_07
if $1="S138" goto *idou_kuni_08
if $1="S139" goto *idou_kuni_09
if $1="S140" goto *idou_kuni_10

if $1="S141" goto *idou_kuni_11
if $1="S142" goto *idou_kuni_12
if $1="S143" goto *idou_kuni_13
if $1="S144" goto *idou_kuni_14
if $1="S145" goto *idou_kuni_15
if $1="S146" goto *idou_kuni_16
if $1="S147" goto *idou_kuni_17
if $1="S148" goto *idou_kuni_18
if $1="S149" goto *idou_kuni_19
if $1="S150" goto *idou_kuni_20

if $1="S151" goto *idou_kuni_21
if $1="S152" goto *idou_kuni_22
if $1="S153" goto *idou_kuni_23
if $1="S154" goto *idou_kuni_24
if $1="S155" goto *idou_kuni_25
if $1="S156" goto *idou_kuni_26
if $1="S157" goto *idou_kuni_27
if $1="S158" goto *idou_kuni_28

goto *sin_loop_01
```

**Comment by Grimm-Knight** [comment]
I tested the fix and it’s working fine now. Thanks!
