### ISSUE TITLE
Gamepad support

### ISSUE THREAD

**Issue by Mihara** [YuriSizuku/OnscripterYuri#28]
Attempting to run OnscripterYuri on an Anbernic RG405M - an ideal device for the job at all other times, one might think - is rather unwieldy, because the builtin gamepad is ignored completely, and all the gamepad-to-touch mappers are extremely unwieldy to use.

Is there any hope of native gamepad support on Android?

**Comment by YuriSizuku** [comment]
I think this have already support joystick. It uses the SDL joystick driver. 
As for supporting the gamepad device, you can see my psv port of ons https://github.com/YuriSizuku/psv-OnscripterJH

**Comment by Mihara** [comment]
Tsukihime certainly ignores every single button press on Android, so while it might use the SDL joystick driver, its buttons don't appear to be actually *mapped* to anything.
