### ISSUE TITLE
Kagetsu Tohya

### ISSUE THREAD

**Issue by EvGem7** [YuriSizuku/OnscripterYuri#8]
Hi! Catched some bugs with Kagetsu Tohya:

Some weird !w900 text:
![image](https://github.com/YuriSizuku/OnscripterYuri/assets/33933105/300fc8e3-a49f-4866-be20-a1835a8aa764)

Some strings are in Japanese:
![image](https://github.com/YuriSizuku/OnscripterYuri/assets/33933105/16ead680-1e5b-479f-a95b-0fe09d30e01c)

OnscripterYuri (linux if this matters) is on the left. On the right there is the native windows binary running.

You can download Kagetsu Tohya, which I'm using, here: https://drive.google.com/file/d/1XEXTVL9KG-aIKJ9fLsj17LjoSI2ucTib/view?usp=sharing

Also, thank you for your work! Being able to read on android is really cool!

**Comment by YuriSizuku** [comment]
Thank you for your testing. 
I think this might be because of the `default.ttf` doesn't contain such charactors.
These texts are not in the script, but in the ons engine. 
The default encoding method is `gbk`. 
You can try option `--enc:sjis`  in command line or change the `default.ttf` with more charactors.

**Comment by EvGem7** [comment]
@YuriSizuku 

Sorry for long answer.

Yeah, `--enc:sjis` helped a bit. This symbol ![image](https://github.com/YuriSizuku/OnscripterYuri/assets/33933105/0c32d1f3-3ce2-407e-b47c-0d9c24212614) appeared:
![image](https://github.com/YuriSizuku/OnscripterYuri/assets/33933105/ed486107-e8ad-486b-b70f-151aedebfac2)
The !w900 is still there though.

Returning to Title menu is still non-English, but it changed:
![image](https://github.com/YuriSizuku/OnscripterYuri/assets/33933105/e0cfad73-8092-43c9-b8d4-c2c69ccb7de5)
> change the default.ttf with more charactors

I don't know, what I can change. All I know is that the windows binary runs fine.

Also, could it be the issue that there are multiple `arc.nsa` files? I mean, there are `arc.nsa` and `arc1.nsa`. Maybe something that's missing is in the second file?

**Comment by EvGem7** [comment]
I discovered that this !w900 string is a command to wait. Here are two videos with comparison. Windows version does a delay in the place where the !w900 string is showed in OnsYuri.

https://github.com/YuriSizuku/OnscripterYuri/assets/33933105/dc647936-9d86-4f25-944d-933f72d5b425

https://github.com/YuriSizuku/OnscripterYuri/assets/33933105/2a8ff735-362b-4d3f-99bb-b51e426ce151

Also, probably I found why this delay isn't handled properly. I downloaded ONScripter Tools from [here](https://kaisernet.org/onscripter/) and used `nscdec nscript.dat` to extract the original script. Here is how this part is written:

```
` The strong sunlight that burns the skin.@
` The wind that comforts my body soaked in sweat.@
` The white smoke coming off the asphalt and !w900
` The shadows of many trees lining the sides of the road.@
```

The `!w900` string is within the text, not on a separate line. I looked through the script and there are other `!w` commands, and those on separate lines seem to work fine.

**Comment by EvGem7** [comment]
Also, I didn't find the "Return to Title Menu" string in the extracted script. Have no idea, where this string is located. :man_shrugging:

**Comment by YuriSizuku** [comment]
> Also, I didn't find the "Return to Title Menu" string (which is in Japanese in OnsYuri for some reason) in the extracted script. Have no idea, where this string is located. 🤷‍♂️

This string might be built-in stirng in onscripter engine.

**Comment by YuriSizuku** [comment]
> I discovered that this !w900 string is a command to wait. Here are two videos with comparison. Windows version does a delay in the place where the !w900 string is showed in OnsYuri.
> 
>  onsyuri.mp4 
>  win.mp4 
> Also, probably I found why this delay isn't handled properly. I downloaded ONScripter Tools from [here](https://kaisernet.org/onscripter/) and used `nscdec nscript.dat` to extract the original script. Here is how this part is written:
> 
> ```
> ` The strong sunlight that burns the skin.@
> ` The wind that comforts my body soaked in sweat.@
> ` The white smoke coming off the asphalt and !w900
> ` The shadows of many trees lining the sides of the road.@
> ```
> 
> The `!w900` string is within the text, not on a separate line. I looked through the script and there are other `!w` commands, and those on separate lines seem to work fine.

The implementation of ns and ons might be a little different.  It might not support the inline command.

**Comment by YuriSizuku** [comment]
I wil close this issue. If any other problems happens, please feel free to add here.
