### ISSUE TITLE
请求支持macOS m1版

### ISSUE THREAD

**Issue by kekeimiku** [YuriSizuku/OnscripterYuri#9]
qwq

**Comment by kekeimiku** [comment]
web版不知道为什么好像不行。一直卡在这里。
![image](https://github.com/YuriSizuku/OnscripterYuri/assets/36557882/ea4646b1-d868-496d-abfd-60ec702c5cbb)

![image](https://github.com/YuriSizuku/OnscripterYuri/assets/36557882/e4de6aaf-8c7b-4eed-beed-c96c4bf4e845)

**Comment by YuriSizuku** [comment]
web版主要用于nginx等服务器，在index文件里面需要指定每个文件的url。
至于为什么没有加入原生mac版，因为我没有mac设备，没法编译测试。

**Comment by kekeimiku** [comment]
```
{
  "title": "onsyuri_web",
  "gamedir": "/saya",
  "savedir": "/saya",
  "args": [],
  "lazyload": true,
  "files": [
    {
      "path": "arc.nsa",
      "url": "http://localhost:8000/saya/arc.nsa"
    },
    {
      "path": "default.ttf",
      "url": "http://localhost:8000/saya/default.ttf"
    },
    {
      "path": "gloval.sav",
      "url": "http://localhost:8000/saya/gloval.sav"
    },
    {
      "path": "nscript.dat",
      "url": "http://localhost:8000/saya/nscript.dat"
    },
    {
      "path": "save1.dat",
      "url": "http://localhost:8000/saya/save1.dat"
    }
  ]
}
```
这样可以玩了，但是不知道为什么存档没有加载。

**Comment by YuriSizuku** [comment]
> ```
> {
>   "title": "onsyuri_web",
>   "gamedir": "/saya",
>   "savedir": "/saya",
>   "args": [],
>   "lazyload": true,
>   "files": [
>     {
>       "path": "arc.nsa",
>       "url": "http://localhost:8000/saya/arc.nsa"
>     },
>     {
>       "path": "default.ttf",
>       "url": "http://localhost:8000/saya/default.ttf"
>     },
>     {
>       "path": "gloval.sav",
>       "url": "http://localhost:8000/saya/gloval.sav"
>     },
>     {
>       "path": "nscript.dat",
>       "url": "http://localhost:8000/saya/nscript.dat"
>     },
>     {
>       "path": "save1.dat",
>       "url": "http://localhost:8000/saya/save1.dat"
>     }
>   ]
> }
> ```
> 
> 这样可以玩了，但是不知道为什么存档没有加载。

因为浏览器没有权限直接修改本地文件，所以存档会挂载到浏览器indexdb里面，本地文件的存档无效。

**Comment by asukaminato0721** [comment]
> 因为浏览器没有权限直接修改本地文件

开个简易 server 就可以了. 或者 RESTful api, http://clash.razord.top 就这么做的.

**Comment by yujincheng08** [comment]
现在支持了。
